# fly.toml app configuration file generated for backend-dream on 2025-06-28T22:57:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-dream'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

# -------- process group definitions ----------

[[services]]
  processes = ["web"]          # expose only web group
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port     = 80
    handlers = ["http"]

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

# -------- process group: worker (Celery) --------
[processes]
  web    = "uvicorn new_backend_ruminate.main:app --host 0.0.0.0 --port 8080"
  worker = "celery -A new_backend_ruminate.worker worker --concurrency=1 --prefetch-multiplier=1 --max-tasks-per-child=1 --pool=prefork --loglevel=info"
