app = "backend-dream"

primary_region = "iad"

[env]
ENV              = "prod"
LOG_LEVEL        = "INFO"

[deploy]
release_command = "alembic upgrade head"

# -------- process group definitions ----------

[[services]]
  processes = ["web"]          # expose only web group
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port     = 80
    handlers = ["http"]

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

# -------- process group: worker (Celery) --------
[processes]
  web    = "uvicorn new_backend_ruminate.main:app --host 0.0.0.0 --port 8000"
  worker = "celery -A new_backend_ruminate.worker worker --loglevel=info"