"""Add modality field to segments table

Revision ID: b9a8ed2a413a
Revises: f0be66df5dda
Create Date: 2025-07-04 11:05:34.031396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a8ed2a413a'
down_revision: Union[str, None] = 'f0be66df5dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_conversation_id', 'conversations', ['id'])
    
    # Add modality column as nullable first
    op.add_column('segments', sa.Column('modality', sa.String(length=10), nullable=True))
    
    # Set existing segments to 'audio' since they were all audio before
    op.execute("UPDATE segments SET modality = 'audio' WHERE modality IS NULL")
    
    # Now make it non-nullable
    op.alter_column('segments', 'modality',
               existing_type=sa.String(length=10),
               nullable=False)
    
    op.alter_column('segments', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('segments', 's3_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('segments', 's3_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('segments', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('segments', 'modality')
    op.drop_constraint('uq_conversation_id', 'conversations', type_='unique')
    # ### end Alembic commands ###
