"""Add missing indices for foreign keys and state

Revision ID: cdbbcaea639a
Revises: 57586095e6f1
Create Date: 2025-07-06 23:28:52.710851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdbbcaea639a'
down_revision: Union[str, None] = '57586095e6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dreams_state'), 'dreams', ['state'], unique=False)
    op.create_index(op.f('ix_interpretation_answers_selected_choice_id'), 'interpretation_answers', ['selected_choice_id'], unique=False)
    op.create_index(op.f('ix_interpretation_questions_dream_id'), 'interpretation_questions', ['dream_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interpretation_questions_dream_id'), table_name='interpretation_questions')
    op.drop_index(op.f('ix_interpretation_answers_selected_choice_id'), table_name='interpretation_answers')
    op.drop_index(op.f('ix_dreams_state'), table_name='dreams')
    # ### end Alembic commands ###
